#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "  Gimme:"
    echo "    gimme [TERM]"
    echo "      picks a task at random having TERM"
    exit
}

TODOTXT_VERBOSE=0

"$TODO_SH" ls "$@" | shuf | head -1
